name: 'Todos'
on: ['push']
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2.3.1'
      - name: 'TODO to Issue'
        uses: 'alstr/todo-to-issue-action@v4.5'
        id: 'todo'
